name: My-GitHub-Basics

env: 
  APPLICATION_NAME    : "My flask"
  DEPLOY_PACKAGE_NAME : "deploy-package-file-ver-${{ github.sha }}"

on: 
  push:
    branches:
      - main
    
jobs:

  my_testing:
   
   runs-on: ubuntu-18.04
   
   steps: 
   - name: Print Hello Message in testing
     run: echo "Hello World From Testing!"
     
   - name: Show what we files we got
     run: ls -lG
     
   - name: Clone the repositore
     uses: actions/checkout@v1
     
   - name: Show what we files we got
     run: ls -lG
     
   - name: Execare few commands
     run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
  
  my_deploy:
    
    runs-on: macos-10.15
    needs: [my_testing]
    env: 
       VAR1 : "My job level variable number 1"
       VAR2 : "My job level variable number 2"
    
    steps:
     - name: Print Hello Message in deploy
       run: echo "Hello World From Deploy!" 
       
     - name: Print my job variable
       run: |
          echo "var 1 = ${{ env.VAR1 }}"
          echo "var 2 = ${{ env.VAR2 }}"
          echo "local var = $LOCAL_VAR"
       env: 
          LOCAL_VAR: "My local level variable 1"
       
     - name: Printing deploy package 
       run: echo "Deploy package is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
     - name: Lets test some packeage if they are here 1
       run: aws --version
       
     - name: Lets test some packeage if they are here 2
       run: zip --version
